### ISSUE TITLE
Notes appearing in middle of scroll field

### ISSUE THREAD

**Issue by mat100payette** [flashflashrevolution/rCubed#1]
**Describe the bug**
Sometimes when starting a song, the notes would not appear outside the screen as usual (without screencut set), but rather in the middle of the scrolling field. This would make it impossible to play as it reduces the scrolling space to about 20% of what it should be.

**Screenshots**
None yet; hard to catch.

**Reproduction Steps**
Haven't managed to reproduce the bug consistently yet.

**Reproduction Rate**
This bug occurs about 5% of the time.

**Expected behaviour**
The notes should always appear at the same position consistently.

**Desktop (please complete the following information):**
 - Platform: Air
 - Version: 1.0.1

**Additional context or comments**
After restarting the song, the notes would return to normal.

**Comment by Zageron** [comment]
As an aside, work I am doing right now should prevent this problem from happening.

**Comment by G-flat** [comment]
Does this problem still occur? If not, I'm voting for closing this issue.

**Comment by Zageron** [comment]
Appears to be fixed.
