### ISSUE TITLE
Add UI feedback for improper values

### ISSUE THREAD

**Issue by TCHalogen** [flashflashrevolution/rCubed#10]
**Overview**
Users get no feedback for invalid options throughout the game; values that may be perceived as valid are instead reset to defaults without any indication that the game has deemed them as invalid.

**Suggestion**
Highlight UI elements containing type-valid values whose setting falls outside of the threshold before resetting to a default. I attempted to add text underneath the erroneous values but quickly realized that space was too limited to provide anything meaningful. An additional hoverable icon indicator can be added to tell them what the issue is.

**Images**
https://i.imgur.com/WG510Bf.png -- note that in this image, the two values highlighted are actually values that will cause the game to revert to the default of 1. That is: scroll speeds less than or equal to 0.1 will reset to 1, and song rates less than 0.1 will reset to 1 as well. There may be others.

**Comment by Zageron** [comment]
@TCHalogen Would positive feedback also be a good concept? Like while the user is typing in the box, be red when it's invalid and be green when it's valid. When the user leaves the box it reverts to regular white.
