### ISSUE TITLE
Way To Change Profiles from r3air engine

### ISSUE THREAD

**Issue by SmexxxyBeast** [flashflashrevolution/rCubed#121]
A way to change profiles directly from the r3 air engine 
Describe your feature!

** Images **
If applicable, please sketch out what you mean in a piece of painting software.
You may be able to just take a screenshot of R3 and draw over it.

**Comment by G-flat** [comment]
@all-contributors please add @SmexxxyBeast for code

**Comment by G-flat** [comment]
@all-contributors please add @SmexxxyBeast for ideas

**Comment by Sploder12** [comment]
@SmexxxyBeast how would you like to see this implemented? I was thinking a button in the context menu that would allow you to return to the login screen and change accounts.

**Comment by SmexxxyBeast** [comment]
I was actually thinking the same thing myself! I wanted to make sure it was
simple enough so everyone regardless of how new they were to the game would
be able to do so and figured that was the easiest way :)
