### ISSUE TITLE
Expiring stored user sessions cannot immediately log into the engine

### ISSUE THREAD

**Issue by TCHalogen** [flashflashrevolution/rCubed#13]
**Describe the bug**
When an a user tells the engine to remember their user credentials, any action that causes the session to expire will correctly prompt the user to reauthenticate — however, after receiving that notice, attempts at authentication will not work as the event callback for the Login button does not fire.

**Reproduction Steps**
- Perform any method that would cause a user's session to expire. In my case, I logged into one version of the engine and told it to remember my credentials, then logged into another version of the engine and also told it to remember my credentials. I imagine something like a password change would also cause this to occur as well.
- Attempt to authenticate. The login button will not perform any action or notify the user of any incorrect information. Upon closure and reopening of the engine, the user's session is no longer stored and they will have to provide their information again to have it remembered.

**Reproduction Rate**
This bug occurs 100% of the time with the given constraints, on both beta and release builds.

**Expected behaviour**
Upon the user being notified that their session has expired, they should be able to authenticate with their credentials as normal.

**Desktop (please complete the following information):**
 - Platform: Air
 - Version: 1.1.1, 1.1.1 (beta)

**Additional context or comments**
One attempt at reproducing this bug actually caused a crash on the Beta build, but the cause of that particular crash has not been determined.

**Comment by Zageron** [comment]
@all-contributors please add @TCHalogen for bug
