### ISSUE TITLE
Settings Reset not Resetting all Options

### ISSUE THREAD

**Issue by Xyr00** [flashflashrevolution/rCubed#144]
**Settings Reset does not reset all options**
Using the "Reset" option to clear user settings does not reset all fields to default values. Each screenshot below shows the values that do not reset when the option to reset is chosen.

**Screenshots**
Screen 1 (Main):
![image](https://user-images.githubusercontent.com/2185274/86019370-8273b000-b9f4-11ea-990d-83191fbf247f.png)
Screen 2 (Visual & Game Modifiers):
![image](https://user-images.githubusercontent.com/2185274/86019856-265d5b80-b9f5-11ea-819d-e7a0c5d5da0d.png)
Screen 3 (Game & Text Colors):
No issues on screen 3

Screen 4 (Other Options)[including dev build screenshot here for reference to include new checkboxes]:
![image](https://user-images.githubusercontent.com/2185274/86020686-3aee2380-b9f6-11ea-99af-8cd76bfad95b.png)

Reset functions as expected for all Editor screens.

**Reproduction Steps**
1. Set settings in one of the above areas
2. Select "Reset" option to clear all settings
3. Above settings will not be cleared

**Reproduction Rate**
This bug occurs 100% of the time.

**Expected behavior**
Settings circled above reset to normal.

**Build Info**
 - Platform: Air
 - Version: Version 0.0.0.8 and newer

**Additional context or comments**
I initially talked with Velocity about this, he warned that user settings is delicate and users can be bricked from accessing the game if fix not done correctly.

**Comment by Zageron** [comment]
While we're in here, could we please change vsync to be on by default?
It probably improves performance across the board for most people.

**Comment by Psycast** [comment]
Fixed in PR #162.
