### ISSUE TITLE
Complete the Friends feature.

### ISSUE THREAD

**Issue by Zageron** [flashflashrevolution/rCubed#15]
Currently the Friends and FriendsMenu classes remain unused.

**Comment by G-flat** [comment]
Progress update:

I've got the Friends menu to work again. Currently, you could see the statuses of all of your friends in that menu. These statuses include 'Online', 'Offline', 'Playing FFR' and 'Playing FFR - [Song name]'.

When clicking a friend entry, it's height increases, but that's it. Is it supposed to show something else on click?

I've shown the menu to a few people in the #dev-chitchat DIscord channel, and they suggested adding colours to the statuses (e.g. green for 'Online', red for 'Offline') and also tabs for looking for friends with a specific status only.

On an unrelated note, @Psycast said you've commented out the Friends menu, but then suggested adding back in for some reason. He considers this menu to be not very useful. Should I continue working on this feature request, or should I close it?

**Comment by Zageron** [comment]
If you've done work on it I'd argue to finishing it and then we can hide it behind a toggle at worst. More features is best, that way we could at least test them out with people and see if they like it. My suggestion for finishing the feature was essentially we should either finish it or get rid of it, though I didn't mention the second part.

**Comment by Zageron** [comment]
Closing this, feel free to reopen.
