### ISSUE TITLE
Button to toggle an override of the settings that introduce flashy effects.

### ISSUE THREAD

**Issue by Zageron** [flashflashrevolution/rCubed#16]
This was a request from @G-flat and TD_Greed (discord).

Feedback on these changes should be sourced from people with epilepsy or sensitivity.
- [ ] A checkbox should be available in settings that removes intense flashing effects from the game.
  - [ ] Receptor animation.
  - [ ] Judge
  - [ ] Current accuracy totals?
  - [ ] Health bar animation slowed down?
  - [ ] Colour's of arrows should be made less vibrant

**Comment by qrrbrbirbel** [comment]
I second the receptor animation, the option to disable it would be very easy on my eyes

**Comment by Zageron** [comment]
This is reliant on the new settings overhaul that @Psycast is working on.

**Comment by Zageron** [comment]
Settings overhaul was finished, so this can proceed any time.
