### ISSUE TITLE
Incorrect Song Info displayed after returning from Game Results

### ISSUE THREAD

**Issue by Psycast** [flashflashrevolution/rCubed#174]
**Describe the bug**
While using a filter for the song selection screen, the incorrect song info is displayed on the right info box when returning from the game results screen back to song selection menu.

**Reproduction Steps**
Follow these steps to reproduce bug:
1. Apply a filter that would exclude a song after it's been played.
2. Play said song and return from the results screen.
3. The first song in the song selection screen will be selected but the song info will be for the old now filtered song.

**Reproduction Rate**
This bug occurs 100% of the time.

**Expected behaviour**
Song info should match the selected song when returning from the results screen.

**Desktop (please complete the following information):**
 - Platform: Air
 - Version: 1.1.1, 1.2.4

**Comment by G-flat** [comment]
@all-contributors please add @Psycast for bug
