### ISSUE TITLE
Sort Songs by Rank!

### ISSUE THREAD

**Issue by bolthyy** [flashflashrevolution/rCubed#195]
I would absolutely love the option to sort songs in the FFR engine by my current LevelRank on that particular song. That way I could see what my lowest ranked songs are that are effecting my average levelrank without needing to find my levelrank page, which is not found in a very intuitive place, in my opinion.

**Comment by G-flat** [comment]
I have implemented the rank sort and several others: sorting by time, song rating, note count, name (case-insensitive), and score. All of these sorts could be done either in ascending or descending order.

@BolthMannn, where would you like the sort options to be placed in the game? There is very little space to be used in the song selection menu, so my first thought was to use the 'Other Options' tab in the options menu, but this might not be what you have in mind.

**Comment by BolthMannn** [comment]
Are new categories able to be added on the left hand side that currently has the three: Genre's, Difficulties, Song Flags? 
Another tab saying ''other'' could be an ideal place to put the new sorting options. If not, other options is probably fine but would likely not be as used if it was in a more obvious spot.

**Comment by Zageron** [comment]
@G-flat Did you finish this?

**Comment by G-flat** [comment]
@Zageron No, I haven't yet. I would be working on this for the 1.3.1 release later.
