### ISSUE TITLE
Music preview while selecting a Song

### ISSUE THREAD

**Issue by maxproske** [flashflashrevolution/rCubed#21]
This feature exists on the Velocity engine, and it would be great to have on R^3 too!

In 2014, Velocity mentioned a possible limitation in pulling part of the SWF down: SWFs break the audio up into very small chunks that are spread out in pieces, the only way to get the audio is to fully load the entire SWF. If the SWF is loaded as a AS2 SWF, then it can be loaded partially, but the menu will drop down to 30fps. It's not ideal, but an alternative is generating a preview file of a reasonable length.

To reduce bandwidth, it could only apply to users who have "Use Local File Caching" enabled.

![screenshot](https://i.imgur.com/UNbNG98.png)

**Comment by Zageron** [comment]
If we put each swf download request into a worker it wouldn't cause any kind of performance hits, especially if we use polling. This would let us load things in the background, and then grab them when we're ready.

**Comment by NSSVelocity** [comment]
Network request are already handled in a off-thread, but doing real-time playback of timeline music in a SWF sets the FPS to the encoded speed aka 30fps for charts. Loading the entire SWF then grabbing the audio skips the framerate limit of playback but can only reliably done once 100% loaded.
