### ISSUE TITLE
Chart not reversed with Reverse mod on

### ISSUE THREAD

**Issue by G-flat** [flashflashrevolution/rCubed#229]
**Describe the bug**
When playing any song with the Reverse mod on, the music is reversed but the chart isn't.

**Reproduction Steps**
Follow these steps to reproduce bug:
1. Enable the Reverse mod in the options menu.
2. Play any song.

**Reproduction Rate**
This bug occurs 100% of the time.

**Expected behaviour**
The chart should also be reversed.

**Desktop (please complete the following information):**
 - Platform: Air
 - Version: 1.3.0

**Comment by Zageron** [comment]
Apparently this is fixed.
