### ISSUE TITLE
Declutter the options menu

### ISSUE THREAD

**Issue by G-flat** [flashflashrevolution/rCubed#230]
**Is your feature based on a frustration?**
Not really, but many players have expressed desire for a simpler, less cluttered options menu.

**If so, Describe the solution you'd like**
There are a few things we could improve on:
- Placement of menu tabs and individual settings: The options menu could follow the one from the Xenon engine, with the menu tabs placed on the left of the screen instead of the top of a box, and with the individual settings put to the right of the menu tabs instead of being underneath them.
- Collapse relevant options into a drop-down box: For example, we could collapse the scroll directions, selectable noteskins and game languages into drop-down boxes since we could only select 1 option out of each group.

**And, Describe alternatives you've considered**
The options menu doesn't have to follow the style of that from the Xenon engine, it could remain the same.

**Comment by Zageron** [comment]
Schedule a design jam for some time and we can fiddle with the best layout concepts.
Could even go all in with any kind of rework.
