### ISSUE TITLE
Add a Short Judgement (Duration) Option

### ISSUE THREAD

**Issue by silentsputnik** [flashflashrevolution/rCubed#231]
The following video compares the duration of judgement text that I've played with for as long as I can remember with the longer duration of 1.3.0. Note that the 'GOOD' judgement is displayed several times longer than previously:
https://youtu.be/KxQhFKhf9_s

Personally, this rather large change makes it difficult for me to play. It would be awesome to have the ability to reduce judgement text duration so that anyone who is bothered by this change can enjoy all of 1.3's new awesome features.

**Comment by Zageron** [comment]
@all-contributors please add @silentsputnik for ideas
