### ISSUE TITLE
"Rank = 1" filter displays the incorrect amount of AAAs within client

### ISSUE THREAD

**Issue by Hawkward0** [flashflashrevolution/rCubed#238]
The following bug has been found within R^3 [1.3.0] Win 32.0.0.170 - Build 2020-06-14 - 1.3

When you apply a "Rank = 1" filter, the number of songs displayed does not match with the combined total number of public/token AAAs in a user's levelranks. The screenshots below will display the incorrect and correct numbers but for clarity, my total AAA count is 1550. (1545 public and 5 token.) With the "Rank = 1" filter applied, the number shown becomes 1258. These numbers are visible below the song list as a means of page sorting.

AAA total (1550) with no filter applied:
![1550 AAAs](https://i.imgur.com/3n4kNkC.jpeg)

The selected filter:
![Rank 1 Filter](https://i.imgur.com/fEGgr8b.jpeg)

AAA total (1258) with filter applied:
![1258 AAAs](https://i.imgur.com/uYcQx92.jpg)

It's worth noting that the number of AAAs displayed (1258) with the filter applied is consistent across the All sub-category within any main category (Song Flags, Genres, Difficulties, etc.) so it is not unique to the AAA sub-category shown in the screenshots.

To reproduce this bug, take note of the number of songs displayed under the AAA sub-category under Song Flags then go under the Filters menu at the top settings bar. Create a "Rank" filter type and make sure "=" is selected from the dropdown provided. Enter 1 in the text field that follows. When you go back to the main song selection screen, you'll notice that the number of songs displayed under that same AAA sub-category under Song Flags will be different, despite rank 1 being synonymous with AAA in FFR's definition.

This bug occurs 100% of the time with the pre-mentioned filter applied. The expectation is that the number of displayed AAA'd songs should not change. In my case, 1550 should remain constant within the AAA sub-category under Song Flags with or without the filter. In short, what the client considers rank 1 does not match with how it flags a AAA.

**Comment by dave936** [comment]
It seems the ranks of songs you've AAA'd displayed in /game/r3/r3-userRanks.v2.php are inconsistent, and this is where the game pulls from - for instance, I have a AAA on Too Tight, yet here it shows me I'm rank 5. No idea what that's based on; if anyone with access to the backend could have a look?

![ffr](https://user-images.githubusercontent.com/50265779/189527973-44090395-07cf-4d05-8d77-6081aff8950d.png)

**Comment by Psycast** [comment]
Fixed.
