### ISSUE TITLE
View notes hit by just the left or right hand on the results screen

### ISSUE THREAD

**Issue by sspenst** [flashflashrevolution/rCubed#239]
Pretty sure my left hand is worse than my right at this game, but I'd like to see how much worse on the results screen. Could add 'L' and 'R' buttons on the left side of the screen to filter keypresses from one hand.

**Comment by Zageron** [comment]
Might make more sense to add a filter that lets you select the "columns" to show to account for different playstyles.

**Comment by Sploder12** [comment]
Gonna do this for the "Game Jam"
