### ISSUE TITLE
Favorite Songs

### ISSUE THREAD

**Issue by Sploder12** [flashflashrevolution/rCubed#24]
When selecting a song there is a button that allows to favorite a song. This could be used while filtering songs or as a new tab in the Genre List.

**Comment by G-flat** [comment]
In the song filter menu, you could use the 'Personal Rating' filter to display songs depending on the ratings you've given to them. These rating range from 0 (no rating) to 5 (max), with increments of 0.5 in between.

This leaves adding a new 'My favourites' tab in the genre list. In your opinion, what is the minimum rating required for a song to be considered a favourite?

**Comment by Zageron** [comment]
Probably a heat symbol. But filtering by 5 star might be more realistic.

**Comment by Xyr00** [comment]
I like Zag's idea. As I mentioned in Discord there are a lot of instances where I think a file is great and fits the song well, and might even be a 5-star quality file to me. But say, for example, I don't like the music itself. Or the length is too long. Or I only "favorite" chiptune files. This would allow me to run favorite & ratings separately. Something like the below, with a hover tool-tip scenario saying "Add to Favorites" (& have it be an outline if not favorited):

![image](https://user-images.githubusercontent.com/2185274/85926311-ae642980-b86c-11ea-830d-916ad68c17a3.png)

![image](https://user-images.githubusercontent.com/2185274/85926316-b3c17400-b86c-11ea-81e1-fed2629bca78.png)

**Comment by G-flat** [comment]
I have asked the OP (@Sploder12) in Discord about their thoughts on implementing this feature request, and they have stated that @Xyr00's idea is what they were looking for, with the fire icon being a heart instead.

**Comment by Zageron** [comment]
Awesome! So whoever wants to take this make sure you assign yourself! :)
