### ISSUE TITLE
Add Division 8 title to Multiplayer lobby

### ISSUE THREAD

**Issue by maxproske** [flashflashrevolution/rCubed#25]
Division 8 was made official during the [12th Official Tournament](http://www.flashflashrevolution.com/vbz/showthread.php?t=151110), and now appears on the [Global Leaderboards](http://www.flashflashrevolution.com/leaderboards/). It would be nice to give Division 8 players the same recognition in-game.

Division Title: Godly
Divsion Color: 0xD2C7AC

**Comment by Zageron** [comment]
@all-contributors please add @maxproske  for suggestion

**Comment by G-flat** [comment]
@all-contributors please add @maxproske for code
