### ISSUE TITLE
Date Localization

### ISSUE THREAD

**Issue by Sploder12** [flashflashrevolution/rCubed#254]
**Is your feature based on a frustration?**
The engine currently only uses D/M/Y format which can be confusing with the website using localized dates.

**If so, Describe the solution you'd like**
The engine switches the format to be localized like the site does.

**And, Describe alternatives you've considered**
More clarification of what format is being used.

**Images**
current (constant D/M/Y)
![image](https://user-images.githubusercontent.com/49347001/104042391-74bf9400-51a8-11eb-89fe-be0c006ceb1d.png)

proposed (localized to M/D/Y)
![image](https://user-images.githubusercontent.com/49347001/104042272-45108c00-51a8-11eb-926a-1f545d5cada4.png)

**Comment by Zageron** [comment]
Localizing time seems like a good idea. However we should use yy/mm/DD to conform to international, and sorting, standard.
