### ISSUE TITLE
Add resources for learning ActionScript 3

### ISSUE THREAD

**Issue by maxproske** [flashflashrevolution/rCubed#26]
Perhaps the greatest source of friction for new contributors will be learning AS3.

It would be helpful to include a section in the README that links to documentation and learning resources (eg. https://www.adobe.com/devnet/actionscript/learning.html).

**Comment by SalemKitkat** [comment]
Couldn't you just enable wiki for that instead of putting it in the readme? Would be more organised and you'd be able to add more resources that way as well as keeping clutter in the readme to a minimum

**Comment by Zageron** [comment]
Yeah we can start a wiki on here.

**Comment by G-flat** [comment]
A wiki page has been added to include learning resources for ActionScript 3. The Home wiki page has also been updated to include a link to the learning resources page.
