### ISSUE TITLE
Add 'Remove Receptor Judgment Animation' button from AF2021 Engine

### ISSUE THREAD

**Issue by goldstinger** [flashflashrevolution/rCubed#287]
@Psycast add the same button from AF2021 Engine to remove the receptor judgment animation so that notes just disappear, and there's no fancy movement/warping of receptors when notes are hit.

This button is described as 'Show Receptors Animations' under 'Visual & Game Modifiers' in AF2021 and by default is set to On.

Tagging Velo so he will remember to add it sometime because this is the only thing really keeping me & a few others from switching to the latest engine.

**Comment by Zageron** [comment]
As an FYI anyone could do this.
https://github.com/Psycast/rCubedAprilFool2021
