### ISSUE TITLE
Add host privileges to MP rooms

### ISSUE THREAD

**Issue by mat100payette** [flashflashrevolution/rCubed#29]
**Is your feature based on a frustration?**
I'm always frustrated when a user joins my MP (Multiplayer) room and doesn't behave properly, as if they owned the room. Such behavior includes not picking files, being mean to others or just spamming messages.

**If so, Describe the solution you'd like**
It would be really helpful to have host privileges such as:

- Muting a user for X seconds in a room
- Kicking out a user from a room
- Banning a user from a room

**And, Describe alternatives you've considered**
The only viable alternative would be to constantly have a MP moderator online to make such actions, but that could be quite the task.

**Comment by G-flat** [comment]
@all-contributors please add @mat100payette for ideas

**Comment by Zageron** [comment]
@all-contributors please add @G-flat  for docs

**Comment by Zageron** [comment]
Reliant on server side extension.
I have a development environment for testing and developing this set up.

**Comment by Psycast** [comment]
This is supported in MP rework.
