### ISSUE TITLE
Incorrect MP Avatars

### ISSUE THREAD

**Issue by Sploder12** [flashflashrevolution/rCubed#300]
The client is sending bad avatar data to the spectators during mp.
It is the client sending since spectators on both 1.3.1 and 1.4.0 see the same wrong avatar.

![image](https://user-images.githubusercontent.com/49347001/122477037-1edfeb00-cf95-11eb-82cc-0b2186ab2653.png)

**Comment by Zageron** [comment]
Seems to be an issue with `https://www.flashflashrevolution.com/avatar_imgembedded.php` for some avatars.
