### ISSUE TITLE
Missing StringID for Game Results filter columns.

### ISSUE THREAD

**Issue by goldstinger** [flashflashrevolution/rCubed#309]
Missing:

game_results_filter_column_L
game_results_filter_column_D
game_results_filter_column_U
game_results_filter_column_R
game_results_filter_column_LHS
game_results_filter_column_RHS
game_results_filter_column_A

Button for them is located in bottom left hand corner of results screen, identified by a giant 'C' in a box, when viewing Accuracy Spread, it is used to filter the Accuracy Spread results specifically to certain columns (Left, Down, Up, Right, Left-Hand, Right-Hand, All)

Default is set to game_results_filter_column_A to show all accuracy results.

**Comment by Zageron** [comment]
@Sploder12 did you add this feature? I forget. I guess the stringids were never added?

**Comment by Sploder12** [comment]
See line 446 of GraphAccuracy.as

The feature has been there for a while, the lang strings need to be added.

**Comment by Zageron** [comment]
Done.
