### ISSUE TITLE
When playing in single-player the Connect/Disconnect messages flood MP.

### ISSUE THREAD

**Issue by Zageron** [flashflashrevolution/rCubed#310]
```
[2:12 PM] * Disconnected
[2:14 PM] * Joined Lobby
```
![image](https://user-images.githubusercontent.com/1892473/122616760-eb0dcf80-d03f-11eb-89e3-cb71d49d6129.png)

Solution:
- Don't print the connect and disconnect messages when going into a single player game.

**Comment by Zageron** [comment]
@Sploder12 Feel free to take this if you're bored.

**Comment by Sploder12** [comment]
I got you
