### ISSUE TITLE
Some judgment animation wonkiness in multiplayer spectate

### ISSUE THREAD

**Issue by goldstinger** [flashflashrevolution/rCubed#313]
Build 2020-06-14

Judgment animations for only "Good" does not clear in Multiplayer spectating. Other judgments (Average, Miss, Boo) clear as intended.

Good clears as intended in Single Player.

![](https://i.imgur.com/oEjO4gf.gif)

**Comment by goldstinger** [comment]
Update on this issue:
Further observing multiplayer matches while spectating, this issue is also happening with "Boo". Again, it doesn't happen in Single Player, or in Multiplayer while participating as a player, only in multiplayer spectating.

**Comment by Psycast** [comment]
Fixed in #335
