### ISSUE TITLE
Status: Results bug for Multiplayer spectate.

### ISSUE THREAD

**Issue by goldstinger** [flashflashrevolution/rCubed#314]
Build 2020-06-14

Once players finish a song in Multiplayer as a Spectator, it does not show Status: Results. In this instance, if anyone starts spectating, or stops spectating & begins spectating again, it starts playing the song again with neither player playing the song/recording live scores.

Should be noted that 'Status: Results' does show up correctly as a player, this may be an issue correlated either to reading information from engines prior to 1.4.0, or specifically a spectator thing since spectators do not visit a result screen, and the flag for setting 'Status: Results' may be there.

**Comment by Zageron** [comment]
This is probably fixed, please re-affirm.

**Comment by Psycast** [comment]
Most likely fixed in MP rework.
