### ISSUE TITLE
Spectate button refuses to work while players are playing song.

### ISSUE THREAD

**Issue by goldstinger** [flashflashrevolution/rCubed#316]
Build 2020-06-14 1.4.0

Normally, hitting 'start spectating' when you are in a room and both players start playing, it should just load the song and jump to wherever in the chart the players are, but in cases where the 'start spectating' button was not pressed while players were loading their files and begin playing, it will not load the song or go to multiplayer spectating.

Tried isolating the case myself and found issue with spectate button working between 2 of my alts starting a song in a room and viewing it as a spectator on 1.4.0, (alts ran flash projector .swf link)

**Comment by goldstinger** [comment]
This bug might be in relation to https://github.com/flashflashrevolution/rCubed/issues/315 as it only happens sometimes, not all the time.

**Comment by Zageron** [comment]
Fixed by #321 and #319

**Comment by Zageron** [comment]
Fixed by #321 and #319
