### ISSUE TITLE
Rare cases of song not ending when both players quit out in Multiplayer

### ISSUE THREAD

**Issue by goldstinger** [flashflashrevolution/rCubed#317]
Build 2020-06-14 1.4.0

Couple repeat cases where both players (not alts) dropped out of a song, and the replay continued without any score calculation happening for both players.

In the first instance, it got to the end of the song and loaded a single player's gameplay, with the avatar & names of players in the lobby. The single player was also present in the lobby, but not playing as a lobby player, they were playing single player while spectating in the lobby. It calculated score properly for player 1 (at the time, the single player) under the actual first lobby player, and showed no score calculation for player 2.

In the second instance, both players for the lobby loaded a new song while the first one was still erroneously playing without score calculation for both players, and the second song loaded and began playing while the first one was also playing. The multiplayer spectate interface restarted and showed judgments/scores correctly for the second song, while still playing audio for the first song. The engine crashed before the second song (and players) finished.

**Comment by Psycast** [comment]
Most likely fixed in MP rework.
