### ISSUE TITLE
Status: Playing stuck for older clients / improper reporting of Status on engines other than 1.4.0

### ISSUE THREAD

**Issue by goldstinger** [flashflashrevolution/rCubed#318]
1.4.0 build 2020-06-14

After completing a song as a player in a multiplayer room, the Status for you is stuck as 'Playing' on all other engines outside of 1.4.0, which makes it impossible to play more than 1 song in a row against anyone using a different engine other than 1.4.0.

It fixes itself if you go to spectating and then re-join as a player, but by god is that annoying to do for every song.

![](https://i.imgur.com/MAlMEdU.png)

**Comment by Zageron** [comment]
This is because of client side state reporting. We may need to send game version with 1.4 clients and if a player doesn't have a version then it does some extra work.

**Comment by Zageron** [comment]
This may be fixed, please confirm.

**Comment by goldstinger** [comment]
Appears fixed on my end as of 1.4.0-beta4, have yet to test it with multiple computers / players
