### ISSUE TITLE
Fix persistent room join issue

### ISSUE THREAD

**Issue by SalemKitkat** [flashflashrevolution/rCubed#32]
**Describe the bug**
Multiplayer rooms keep player data even when it doesnt exist anymore.

**Screenshots**
http://prntscr.com/sdbn7i

**Reproduction Steps**
Follow these steps to reproduce bug:
1. Go to Multiplayer Lobby
2. Click on 'Create Room' with any name
3. Leave the room so its destroyed (Without going to spectator)
4. Attempt to join any other MP room with a free slot as a player
5. Error message says you cannot be a player in more than 1 game

**Reproduction Rate**
This bug occurs 100% of the time.

**Expected behaviour**
Multiplayer room session to be destroyed when its non existant, so you join another MP room
without having to disconnect and reconnect.

**Desktop (please complete the following information):**
 - Platform: Air
 - Version: 1.1.1

**Additional context or comments**
No other comments

**Comment by dave936** [comment]
Fix soon for this!

**Comment by Zageron** [comment]
@all-contributors please add @maxproske for bug

**Comment by Zageron** [comment]
@all-contributors please add @SalemKitkat  for bug
