### ISSUE TITLE
Alt-Engine Scores do not Record

### ISSUE THREAD

**Issue by Zageron** [flashflashrevolution/rCubed#324]
Scores obtained on an alternate engine (such as FFRMania, Team Blaze, etc) are not being recorded to the alt engine leaderboards. Tried with 1.3.0 with all options the exact same and was able to record scores normally whereas scores would not record with 1.4.0 beta 2.

Ask Jess#2396 on Discord for more details.

**Comment by goldstinger** [comment]
1.4.0-beta4 & 1.5.0-beta1 are both recording scores on my end.
