### ISSUE TITLE
Write name of in-progress song details to text file

### ISSUE THREAD

**Issue by TCHalogen** [flashflashrevolution/rCubed#33]
**Is your feature based on a frustration?**
There's no real way to output details about a song to a source that can be utilized in a stream. Adding a text file whose contents can be targeted as a stream source will allow players access to incorporate them into their streams.

**If so, Describe the solution you'd like**
Provide a now-playing.txt at the root of the engine that allows users to specify an output template with properly named variables that can be replaced when a song starts. Accommodate for white space to allow for the highest amount of flexibility.

> Song: {song} / Artist: {author} / Stepartist: {stepfile_by} / Length: {length}

Would produce the following output (bold to emphasize replacements, not implying that bold should be a thing): Song: **VIS--CRACKED** / Artist: **Frums** / Stepartist: **Dragolord** / Length: **2:59**

> Song: {song}
> Artist: {author}
> Stepartist: {stepfile_by}
> Length: {length};

Would produce the following output (bold to emphasize replacements, not implying that bold should be a thing):

Song: **VIS--CRACKED**
Artist: **Frums**
Stepartist: **Dragolord**
Length: **2:59**

The more variables that are given, the more interactivity that is gained.

**Comment by TCHalogen** [comment]
Adding a comment to this for an additional measure of clarification: the details should be stored game-side, and the output should only occur when the song is playing. This would provide a more graceful handling of most people's streams when they are in fact not playing a song (there's no need to have a now playing context when you're not playing any particular song).

**Comment by Zageron** [comment]
Interesting, this should be easy enough.

1. Local folder for non-installed games.
2. AppData folder for installed games. (Secondary target for when steam release higher on priority.)
