### ISSUE TITLE
Unable to Display File(s) Added to Queue

### ISSUE THREAD

**Issue by Snupeh** [flashflashrevolution/rCubed#336]
**Describe the bug**

After adding file(s) to the queue, the desired function cannot be performed when clicking the "Queue" button on the top right (next to the search button) to see which file(s) has been added to the queue.

[Video](https://youtu.be/eco-Bs4KqOw)

**Expected behaviour**

When the "Queue" button is clicked, the songs added to the queue should be visible.

**Desktop**

 - Version: 1.4.2

**Comment by Zageron** [comment]
What's your active filter?

**Comment by Snupeh** [comment]
**Filter**

FILTERS -> Add Filter Type: -> Song Flags: Doesn't Contain, AAA

This was the filter I used as usual, but I didn't think it would give such an output. Afterwards, I applied the same operations again without selecting any filter, the result was the same.

**Comment by Psycast** [comment]
Fixed with commit 15af103fcee78c04c4a0f092df610a666838d68e.
