### ISSUE TITLE
Multiplayer room scrollbar doesn't always auto-scroll to new messages

### ISSUE THREAD

**Issue by mat100payette** [flashflashrevolution/rCubed#34]
**Describe the bug**
The scrollbar in multiplayer rooms stops scrolling down automatically after some UI actions from the user.

**Reproduction Steps**
Follow these steps to reproduce bug:
1. Go in a multiplayer room and make sure the chat's text has become tall enough for the scrollbar to move.
2. Go to the PLAY or TOKENS tab (possibly more ways to trigger but these I have tested on 2 versions and computers), and come back to the MP tab.
3. Have someone else type things in that same room.
4. The scrollbar is now stuck and all the new text that's written cannot be seen unless you manually scroll down so that it starts following the latest messages again.

**Reproduction Rate**
This bug occurs 100% of the time.

**Expected behaviour**
The scrollbar should always scroll down to the newest messages unless it was Manually scrolled up to read previous messages. Once the scrollbar is set to the very bottom of the chat, it should Always scroll automatically no matter what you are doing in the interface.

**Desktop (please complete the following information):**
 - Platform: Air
 - Version: 1.1.1 and prior versions too

**Comment by G-flat** [comment]
@mat100payette, I've tried replicating this bug in the current development build, but my attempts were unsuccessful. Perhaps this bug is gone?

Maybe we could find some other people to do the testing, just to confirm whether the bug is indeed fixed.

**Comment by G-flat** [comment]
Ignore my comment, I got the bug now.
