### ISSUE TITLE
Settings: Notes/Receptors move during resize

### ISSUE THREAD

**Issue by JustinAFaulkner** [flashflashrevolution/rCubed#355]
**Describe the bug**
Notes/Receptors move around the window during resize

**Screenshots**
[Video from Discord](https://discord.com/channels/196381154880782336/693641317636505629/1063808169123512320)

**Reproduction Steps**
Follow these steps to reproduce bug:
1. Go to 'Settings > Input' or 'Settings > Noteskin'
2. Resize the client window and watch the arrows move

**Expected behaviour**
Arrows stay anchored with screen position changing

**Version tested against:**
 - R3 Air 1.4.5 (error occurs)
 - R3 Air 1.4.4 (error does not occur)

**Comment by Psycast** [comment]
Fixed in 41b06b9a921c42727a5ed42591c8df711fbfc790
