### ISSUE TITLE
Add automatic autofail when raw goods exceeds current song personal best raw good count

### ISSUE THREAD

**Issue by TCHalogen** [flashflashrevolution/rCubed#38]
Addendum to issue #23 -
> Just as a bonus (that we've discussed briefly), it would be really nice to have some sort of checkbox for autofail that ignores all other autofail inputs and takes your PB (Personal Best) in raw goods as the autofail value. That way, a player wouldn't have to manually input their PB for every song when going for new best scores.

**Comment by Zageron** [comment]
@TCHalogen Doing some maintenance, I assume this is not completed yet?
