### ISSUE TITLE
Rank not showing up properly in Results Screen when on a language other than English

### ISSUE THREAD

**Issue by NotSpiralingEnough** [flashflashrevolution/rCubed#380]
**Describe the bug**
If the game is set to a language other than English, the Rank does not show up properly in the Results Screen, showing just "Rank" instead of "Rank: [number]"

**Screenshots**
[French](https://media.discordapp.net/attachments/208016019988414464/1224755548038107206/image.png?ex=661ea57d&is=660c307d&hm=615585ba604494c901667e4a95732bd6bdaa7996a9172bbab9731adf5f100d4a&=&format=webp&quality=lossless)
[Japanese](https://media.discordapp.net/attachments/208016019988414464/1224755548298416292/image.png?ex=661ea57d&is=660c307d&hm=68dbfd33eba5355cdfa55e751e1eca98b7bd85082cea44ff356575c0edac6f2c&=&format=webp&quality=lossless)
[Spanish](https://media.discordapp.net/attachments/208016019988414464/1224755548566716597/image.png?ex=661ea57d&is=660c307d&hm=9471994bc8b3460a15ea161770807b1b5fe87ced27285c86cb230a2e6ea59e6a&=&format=webp&quality=lossless)
[Polish](https://media.discordapp.net/attachments/208016019988414464/1224755548847607960/image.png?ex=661ea57d&is=660c307d&hm=160f118963b14bf261930bafeec4d8009a8f9322c764c6ab6c26b72772a6d5d1&=&format=webp&quality=lossless)

**Reproduction Steps**
Follow these steps to reproduce bug:
1. Go to Miscellaneous in Settings
2. Change "Game Language" to a language other than English
3. Play a song

**Reproduction Rate**
This bug occurs 100% of the time.

**Expected behaviour**
Rank should show up properly in the style of "Rank: [number]"

**Desktop (please complete the following information):**
 - Platform: Air
 - Version: 2.0.1

**Comment by Psycast** [comment]
Should be fixed, the main string used for that text changed to also include the value, and the translations weren't updated to match.
