### ISSUE TITLE
Custom noteskins misbehavior

### ISSUE THREAD

**Issue by TCHalogen** [flashflashrevolution/rCubed#4]
**Describe the bug**
There are two symptoms associated with the same issue here: custom noteskins are not loading properly in the game.

Custom noteskins that are imported into FFR for use through the **Edit Custom Noteskin > Import JSON** feature do not display in-game properly, depending on when they are being used.

- If the user had a custom noteskin as their selected noteskin prior to loading their game, the receptors of the custom noteskin will show and react as custom noteskins do; however, the colored notes indicating the chart's rhythms are invisible and will scroll by as such. Attempting to import a custom noteskin in this situation will do absolutely nothing -- the receptors will show, but the actual scrolling notes will not.

- If the user selects a "native" (already existing, non-custom) noteskin before changing to a custom noteskin, the user's custom noteskin will load with the proper images but the images will not follow the rules in place with regards to rotation, and all arrows will face in one direction (the 0° rotation).

**Video**
https://www.youtube.com/watch?v=xo_nSdFFEN0

**Reproduction Steps**
- **Invisible Custom Noteskin:** Have a custom noteskin selected when the game is loaded, and select a song. The receptors will display, but the notes will not.

- **Improperly Rotated Custom Noteskin:** Select an existing non-custom noteskin, play a song, then select a custom noteskin and play a song. The custom noteskin will load with all assets following their 0° rotation (i.e. all arrows pointing downward on a normal left/down/up/right setup).

**Reproduction Rate**
Both issues listed here are reproduced 100% of the time with their given constraints.

**Expected behaviour**
The expected behavior is for the game's noteskins to render with proper rotation on screen.

**Desktop:**
 - Platform: Air
 - Version: 1.1.1

**Comment by Zageron** [comment]
Note: This bug experienced on a private beta which was improperly tagged accidentally.

**Comment by Zageron** [comment]
Blitting has been abandoned for now so feel free to reopen this if necessary.
