### ISSUE TITLE
'Multiplayer Connection Lost' error message pops up when songs start playing

### ISSUE THREAD

**Issue by G-flat** [flashflashrevolution/rCubed#49]
**Describe the bug**
When songs start playing on FFR R^3 Air 1.2.1, an error message pops up that reads 'MP Error: Multiplayer Connection Lost'.

**Screenshots**
![](https://i.imgur.com/vAZmlUG.png)
![](https://i.imgur.com/hXgL5jU.png)

**Reproduction Steps**
Follow these steps to reproduce bug:
1. Load any song.
2. When the song finishes loading and starts playing, the error message should pop up.

**Reproduction Rate**
This bug occurs 100% of the time.

**Expected behaviour**
This error message should not pop up when songs start playing.

**Desktop (please complete the following information):**
 - Platform: Air
 - Version: 1.2.1

**Additional context or comments**
The second screenshot shows the disconnection and reconnection messages in the Multiplayer Lobby. They appear when these error messages pop up, and are also 100% reproducible.

These error messages also pop up in the following scenarios, and are 100% reproducible:

1. Quit a song to go to the results screen and either click 'Replay song' or press the keybinding for restarting songs.
2. Click 'Spectator Editor', 'Multiplayer Editor' or 'Editor' in the options menu.

**Comment by dave936** [comment]
I'll try and take this one

**Comment by Zageron** [comment]
@all-contributors please add @G-flat for bug
@all-contributors please add @dave936 for code

**Comment by Zageron** [comment]
@all-contributors please add @G-flat for bug
