### ISSUE TITLE
Search button does not autofocus on the associated textbox

### ISSUE THREAD

**Issue by mat100payette** [flashflashrevolution/rCubed#5]
**Describe the bug**
In the Play menu, when you want to search for a song, you click on the Search button. However, the focus is not automatically set to the textbox underneath it.

**Reproduction Steps**
Follow these steps to reproduce bug:
1. Go to Play tab
2. Click on Search button
3. Try to type something

**Reproduction Rate**
This bug occurs 100% of the time.

**Expected behaviour**
A click on the Search button should set the focus to the textbox, since it is implied that the user will want to type something to filter the song, and then select the filter type (as they are in that order from top to bottom). That way, the user has one less action to do whenever they want to search for songs.

**Desktop (please complete the following information):**
 - Platform: Air
 - Version: 1.1.1

**Comment by Zageron** [comment]
Thaks for the report! :)

**Comment by Zageron** [comment]
@all-contributors please add @mat100payette for bug
