### ISSUE TITLE
Locked songs in song select become glitched when using arrow keys to navigate

### ISSUE THREAD

**Issue by goldstinger** [flashflashrevolution/rCubed#53]
**Describe the bug**
When a locked song that shows the prompt to unlock it is in the song select menu, using arrow keys to navigate the songs causes the text boxes to glitch for that specific song worse and worse the more arrow key inputs are used while it stays on screen.

**Screenshots**
![Image](https://i.imgur.com/Ct2UAX1.png)
![Image2](https://i.imgur.com/84JtqW2.png)

**Reproduction Steps**
Follow these steps to reproduce bug:
1. Go to a part of the music menu that contains a locked song.
2. Click on a song name that is not locked, or navigate to a menu that contains 100% locked songs.
3. Use the arrow keys to navigate to the song that is locked.
4. Press down and up on the arrow keys consecutively to deselect and re-select the locked song. Graphics will worsen the more times the locked song is selected/highlighted this way.

**Reproduction Rate**
This bug occurs 100% of the time.

**Expected behaviour**
It should highlight like any song that's being selected, and then un-highlight when navigated away from it. Or, not highlight at all.

**Desktop (please complete the following information):**
 - Platform: Air
 - Version: 1.2.1 (Inherited issue from 1.0.1)

**Additional context or comments**
OS Name Microsoft Windows 7 Home Premium
Version 6.1.7601 Service Pack 1 Build 7601
Other OS Description Not Available
OS Manufacturer Microsoft Corporation
System Name USER-PC
System Manufacturer MSI
System Model MS-7A70
System Type x64-based PC
Processor Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz, 3601 Mhz, 4 Core(s), 8 Logical Processor(s)
BIOS Version/Date American Megatrends Inc. A.10, 05/12/2016
SMBIOS Version 3.0
Windows Directory C:\Windows
System Directory C:\Windows\system32
Boot Device \Device\HarddiskVolume2
Locale Canada
Hardware Abstraction Layer Version = "6.1.7601.24117"
User Name User-PC\User
Time Zone Eastern Daylight Time
Installed Physical Memory (RAM) 16.0 GB
Total Physical Memory 16.0 GB
Available Physical Memory 11.4 GB
Total Virtual Memory 31.9 GB
Available Virtual Memory 26.3 GB
Page File Space 16.0 GB
Page File C:\pagefile.sys

**Comment by G-flat** [comment]
I have a fix for this. Could a dev assign this issue to me? Thanks!
