### ISSUE TITLE
Notes move under receptors

### ISSUE THREAD

**Issue by G-flat** [flashflashrevolution/rCubed#55]
**Describe the bug**
When playing a song on FFR R^3 Air 1.2.1, the notes move under their receptors instead of moving above them.

**Screenshots**
![behind](https://user-images.githubusercontent.com/63449095/83371528-37667d00-a3f5-11ea-80b2-7673d4811da6.png)

**Reproduction Steps**
Follow these steps to reproduce bug:
1. Play any song.
2. The notes should move behind their receptors.

**Reproduction Rate**
This bug occurs 100% of the time.

**Expected behaviour**
The notes should move above their receptors, which is the behaviour exhibited from previous versions up to this one.

**Desktop (please complete the following information):**
 - Platform: Air
 - Version: 1.2.1

**Additional context or comments**
Turning on the 'Dark' mod under 'Game Visual Mods' also show this issue, and this is 100% reproducible.

**Comment by goldstinger** [comment]
Needs Beta label.

Verified not an issue on both 1.0.1 and 1.1.1.

![Image](https://i.imgur.com/ZgyoMnn.png)

**Comment by Zageron** [comment]
Thanks, this is resolved in the blitting patch.
