### ISSUE TITLE
Reverse Mod destroys Play field and softlocks the game

### ISSUE THREAD

**Issue by goldstinger** [flashflashrevolution/rCubed#56]
**Describe the bug**
When selecting Reverse Mod in options menu, and then starting a song with it, the game will override your play field settings to put almost everything in the top left corner, will generate no arrows/notes, and force the game into a softlock, as it will refuse to back out of the Game Interface to the results page or the main menu.

**Screenshots**
![Image](https://i.imgur.com/oiriTly.png)

**Reproduction Steps**
Follow these steps to reproduce bug:
1. Go to Options
2. Turn on 'Reverse' at the bottom of the 2nd column of options under 'Visual & Game Modifiers'
3. Start any song with the modifier active/on
4. Enjoy your softlocked game

**Reproduction Rate**
This bug occurs 100% of the time.

**Expected behaviour**
Should play the audio for the song in reverse, along with the notes for the song in reverse. Currently, only plays the audio in reverse and breaks everything else/makes the game unplayable.

Probably just remove Reverse Mod from the game.

**Desktop (please complete the following information):**
 - Platform: Air
 - Version: Any version that contains Reverse Mod (Tested on 1.0.1)

**Additional context or comments**
OS Name Microsoft Windows 7 Home Premium
Version 6.1.7601 Service Pack 1 Build 7601
Other OS Description Not Available
OS Manufacturer Microsoft Corporation
System Name USER-PC
System Manufacturer MSI
System Model MS-7A70
System Type x64-based PC
Processor Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz, 3601 Mhz, 4 Core(s), 8 Logical Processor(s)
BIOS Version/Date American Megatrends Inc. A.10, 05/12/2016
SMBIOS Version 3.0
Windows Directory C:\Windows
System Directory C:\Windows\system32
Boot Device \Device\HarddiskVolume2
Locale Canada
Hardware Abstraction Layer Version = "6.1.7601.24117"
User Name User-PC\User
Time Zone Eastern Daylight Time
Installed Physical Memory (RAM) 16.0 GB
Total Physical Memory 16.0 GB
Available Physical Memory 11.4 GB
Total Virtual Memory 31.9 GB
Available Virtual Memory 26.3 GB
Page File Space 16.0 GB
Page File C:\pagefile.sys

**Comment by Zageron** [comment]
For now I wonder if we should hide the reverse mod option since it's a softlock and doesn't work anyway. Easy fix for someone new to tackle.

**Comment by Xyr00** [comment]
Since we've already hidden Reverse Mod perhaps the good first issue tag should be removed? Unless you still think this could be an easy fix, but I suspect not.

**Comment by SalemKitkat** [comment]
It might be more of a specific environment issue more than a game code issue, but I'll continue looking into it a bit more.
