### ISSUE TITLE
Worsened gameplay performance when the Minestorm noteskin is used

### ISSUE THREAD

**Issue by G-flat** [flashflashrevolution/rCubed#59]
**Describe the bug**
When using the Minestorm noteskin in FFR R^3 Air 1.2.1, gameplay performance is severely degraded.

**Screenshots**
When playing with a noteskin other than Minestorm:
![delta](https://user-images.githubusercontent.com/63449095/83397523-58988f00-a430-11ea-9ed2-b8d4a5d05d4b.gif)

When playing with the Minestorm noteskin:
![mine](https://user-images.githubusercontent.com/63449095/83398101-4f5bf200-a431-11ea-9eb7-399265132759.gif)

**Reproduction Steps**
Follow these steps to reproduce bug:
1. Select the Minestorm noteskin in the settings menu.
2. Play any song.
3. Gameplay should become stuttery.

**Reproduction Rate**
This bug occurs 100% of the time.

**Expected behaviour**
Gameplay performance when using the Minestorm noteskin should be just as good as using any other noteskin.

**Desktop (please complete the following information):**
 - Platform: Air
 - Version: 1.2.1

**Additional context or comments**
Sometimes, when the noteskin previewer displays the Minestorm noteskin, the noteskin's animation might become stuttery, similar to the second screenshot. I couldn't reproduce this though.

**Comment by Zageron** [comment]
Nice bug report, thanks very much!

**Comment by NSSVelocity** [comment]
I did a change how this noteskin was done, which is currently live. If you can detail how the changes affect performance that would be fantastic. This noteskin is tricky compared to the others as it's the only animated one in the game at the current time.

**Comment by G-flat** [comment]
Tried playing songs with the Minestorm noteskin again, and the same performance issue still persists.
