### ISSUE TITLE
Note scaling stuck at 100%

### ISSUE THREAD

**Issue by TCHalogen** [flashflashrevolution/rCubed#6]
**Describe the bug**
Note scale for all noteskins is locked to 100% for scrolling notes. Receptors adjust to the user's desired note scale, but notes retain their full size, creating a crammed notefield that is increasingly difficult to read.

**Video**
https://www.youtube.com/watch?v=x2zY9oiJLjE

**Reproduction Steps**
Go to the **Options** menu and set the **Note Scale** slider to any value under 100%, then either play a song, or click **Editor** and press on the keys corresponding to your in-game setup. The arrows will scroll up the playfield at 100% note scaling.

**Reproduction Rate**
This bug occurs 100% of the time.

**Expected behaviour**
Both the receptors and the scrolling notes should be scaled to the same value when the **Note Scale** option is set to any non-100% value.

**Desktop (please complete the following information):**
 - Platform: Air
 - Version: 1.1.1 (beta)?

**Comment by Zageron** [comment]
Excellent, thanks for the report.
