### ISSUE TITLE
Login screen becomes unresponsive once when session expires

### ISSUE THREAD

**Issue by G-flat** [flashflashrevolution/rCubed#60]
**Describe the bug**
When the session token in FFR Air R^3 1.1.1 has expired, the login screen would become unresponsive when a valid username and password combo is keyed in and the login button is pressed. The program needs to be restarted and the user credentials need to be entered again for logins to work.

**Reproduction Steps**
Follow these steps to reproduce bug:
1. Play until your session has expired.
2. **Without closing the game**, try to re-login with your credentials.
3. You should be stuck at the login screen and not be able to login unless you restart the game and re-login again.

**Reproduction Rate**
Every time my session has expired, I've encountered this bug. Not sure if it's 100% reproducible though.

**Expected behaviour**
Logins should succeed whenever the username and password combo provided is correct.

**Desktop (please complete the following information):**
 - Platform: Air
 - Version: 1.1.1 (might happen in other versions as well, but this is unverified)

**Comment by NSSVelocity** [comment]
Already fixed in repo, Will be in the next update.
