### ISSUE TITLE
Token Display Box Incorrect Height

### ISSUE THREAD

**Issue by Xyr00** [flashflashrevolution/rCubed#69]
**Describe the bug**
Current display of tokens in MenuTokens does not scale to be long enough when token descriptions exceed 4-5 lines of text.

**Screenshots**
![image](https://user-images.githubusercontent.com/2185274/84533366-feac8a80-acb5-11ea-96e2-b94c5e3c1f9d.png)

**Reproduction Steps**
Follow these steps to reproduce bug:
1. Go to 'Tokens' menu option
2. Scroll down list to a token with requirement description longer than 4-5 lines

**Reproduction Rate**
100%

**Expected behaviour**
Box should scale for entire description.

**Desktop (please complete the following information):**
 - Platform: Air
 - Version: unsure - current development build in master branch

**Comment by Zageron** [comment]
@all-contributors please add @Xyr00  for bug and code
