### ISSUE TITLE
Add checkbox for vertically flipping the marker result graph

### ISSUE THREAD

**Issue by G-flat** [flashflashrevolution/rCubed#72]
**Is your feature based on a frustration?**
Not really a frustration, but more of making the marker result graph more intuitive mainly for downscroll players like me.

**If so, Describe the solution you'd like**
Add a checkbox for users to vertically flip the marker result graph.

**Images**
The new checkbox:
![new_option](https://user-images.githubusercontent.com/63449095/84557804-95358600-ad60-11ea-92c6-1028a824af5d.png)

The original, unflipped marker result graph:
![original](https://user-images.githubusercontent.com/63449095/84557808-9797e000-ad60-11ea-8689-a3874921b504.png)

The vertically flipped marker result graph:
![new](https://user-images.githubusercontent.com/63449095/84557811-9ebeee00-ad60-11ea-971f-85b0c17bc096.png)

The unflipped marker result graph with misses at the top:
![original2](https://user-images.githubusercontent.com/63449095/84559156-05e1a000-ad6b-11ea-826a-2716b7875e93.png)

The vertically flipped marker result graph with misses at the bottom:
![new2](https://user-images.githubusercontent.com/63449095/84559163-0c701780-ad6b-11ea-9796-177a21c5e4a1.png)

**Comment by Zageron** [comment]
Would like to enshrine my opinion that the miss row should be where the miss actually occurs based on scroll direction.

Have you considered instead of a checkbox, just checking to see what scroll direction the user has set? (If up, if down etc...)

**Comment by G-flat** [comment]
I considered that before, so I made a poll a long time ago in Discord to ask whether the marker result graph should only be flipped for downscroll. The majority of responses I got at the time voted instead for the player to decide whether to flip the graph on their own. This is why I haven't done any scroll direction checking for this feature.

**Comment by G-flat** [comment]
@all-contributors please add @G-flat for ideas

**Comment by G-flat** [comment]
@all-contributors please add @G-flat for ideas and code
