### ISSUE TITLE
The Save Replay button should be greyed out rather than absent when there is no replay to save.

### ISSUE THREAD

**Issue by Zageron** [flashflashrevolution/rCubed#81]
**Is your feature based on a frustration?**
No, just a visual ambiguity.

**If so, Describe the solution you'd like**
Have the button be un-clickable and darkened.

** Images **
![image](https://user-images.githubusercontent.com/1892473/84620578-433e4e80-ae8d-11ea-9935-82c8b3d1d1de.png)
![image](https://user-images.githubusercontent.com/1892473/84620615-54875b00-ae8d-11ea-8b7a-401f6dc9fd49.png)

**Comment by dave936** [comment]
I'll take this

**Comment by G-flat** [comment]
@all-contributors please add @Zageron for ideas
