### ISSUE TITLE
Highlight personal best scores

### ISSUE THREAD

**Issue by G-flat** [flashflashrevolution/rCubed#86]
**Is your feature just a cool thing you want?**
Definitely! I think we could spice up the highscores tab and popup by highlighting your own personal best scores there.

**Images**
Highlighted personal best score in the highscores tab:
![highlighted_PB_song_select](https://user-images.githubusercontent.com/63449095/84718251-bb4e6680-afaa-11ea-819f-b56bcac9f0d8.png)

Highlighted personal best score in the highscores popup:
![highlighted_PB_highscore_popup](https://user-images.githubusercontent.com/63449095/84718265-c1444780-afaa-11ea-8108-f1145596d8ca.png)

**Comment by Zageron** [comment]
Could we also artificially place your score at the top if you're tied for first?

**Comment by mat100payette** [comment]
Although it was discussed in discord, I'll just put here that there is disagreement from a few people (including myself) on @Zageron 's suggestion, since that breaks the natural time-based ordering most people are used to.

**Comment by G-flat** [comment]
I have made a post both in our Discord server's **feature-discussion** channel and in the forum's FFR suggestions thread. The responses I've garnered are low in number, and all of them were not supportive of this additional suggestion. Therefore, I will not be adding this additional feature, unless players have an interest for it in the future.
